/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutUs {
    }
    interface AppAbout {
    }
    interface BookAppointment {
    }
    interface CircleCard {
    }
    interface DoctorList {
    }
    interface ImageShow {
    }
    interface LogoLogin {
    }
    interface MyAdminnav {
        "backColor": string;
        "fontFamily": string;
        "fontSize": string;
        "textColor": string;
    }
    interface MyAppointment {
    }
    interface MyContactform {
    }
    interface MyError {
        "message": string;
    }
    interface MyFeedback {
    }
    interface MyFooter {
        "Color": string;
    }
    interface MyHeading {
        "text": string;
    }
    interface MyHome {
    }
    interface MyImage {
    }
    interface MyLogin {
        "name": string;
    }
    interface MyNavbar {
        "backColor": string;
        "fontFamily": string;
        "fontSize": string;
        "textColor": string;
    }
    interface MyRegister {
    }
    interface MyUser {
    }
    interface OptionButtons {
    }
    interface ShowDoctor {
    }
}
declare global {
    interface HTMLAboutUsElement extends Components.AboutUs, HTMLStencilElement {
    }
    var HTMLAboutUsElement: {
        prototype: HTMLAboutUsElement;
        new (): HTMLAboutUsElement;
    };
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLBookAppointmentElement extends Components.BookAppointment, HTMLStencilElement {
    }
    var HTMLBookAppointmentElement: {
        prototype: HTMLBookAppointmentElement;
        new (): HTMLBookAppointmentElement;
    };
    interface HTMLCircleCardElement extends Components.CircleCard, HTMLStencilElement {
    }
    var HTMLCircleCardElement: {
        prototype: HTMLCircleCardElement;
        new (): HTMLCircleCardElement;
    };
    interface HTMLDoctorListElement extends Components.DoctorList, HTMLStencilElement {
    }
    var HTMLDoctorListElement: {
        prototype: HTMLDoctorListElement;
        new (): HTMLDoctorListElement;
    };
    interface HTMLImageShowElement extends Components.ImageShow, HTMLStencilElement {
    }
    var HTMLImageShowElement: {
        prototype: HTMLImageShowElement;
        new (): HTMLImageShowElement;
    };
    interface HTMLLogoLoginElement extends Components.LogoLogin, HTMLStencilElement {
    }
    var HTMLLogoLoginElement: {
        prototype: HTMLLogoLoginElement;
        new (): HTMLLogoLoginElement;
    };
    interface HTMLMyAdminnavElement extends Components.MyAdminnav, HTMLStencilElement {
    }
    var HTMLMyAdminnavElement: {
        prototype: HTMLMyAdminnavElement;
        new (): HTMLMyAdminnavElement;
    };
    interface HTMLMyAppointmentElement extends Components.MyAppointment, HTMLStencilElement {
    }
    var HTMLMyAppointmentElement: {
        prototype: HTMLMyAppointmentElement;
        new (): HTMLMyAppointmentElement;
    };
    interface HTMLMyContactformElement extends Components.MyContactform, HTMLStencilElement {
    }
    var HTMLMyContactformElement: {
        prototype: HTMLMyContactformElement;
        new (): HTMLMyContactformElement;
    };
    interface HTMLMyErrorElement extends Components.MyError, HTMLStencilElement {
    }
    var HTMLMyErrorElement: {
        prototype: HTMLMyErrorElement;
        new (): HTMLMyErrorElement;
    };
    interface HTMLMyFeedbackElement extends Components.MyFeedback, HTMLStencilElement {
    }
    var HTMLMyFeedbackElement: {
        prototype: HTMLMyFeedbackElement;
        new (): HTMLMyFeedbackElement;
    };
    interface HTMLMyFooterElement extends Components.MyFooter, HTMLStencilElement {
    }
    var HTMLMyFooterElement: {
        prototype: HTMLMyFooterElement;
        new (): HTMLMyFooterElement;
    };
    interface HTMLMyHeadingElement extends Components.MyHeading, HTMLStencilElement {
    }
    var HTMLMyHeadingElement: {
        prototype: HTMLMyHeadingElement;
        new (): HTMLMyHeadingElement;
    };
    interface HTMLMyHomeElement extends Components.MyHome, HTMLStencilElement {
    }
    var HTMLMyHomeElement: {
        prototype: HTMLMyHomeElement;
        new (): HTMLMyHomeElement;
    };
    interface HTMLMyImageElement extends Components.MyImage, HTMLStencilElement {
    }
    var HTMLMyImageElement: {
        prototype: HTMLMyImageElement;
        new (): HTMLMyImageElement;
    };
    interface HTMLMyLoginElement extends Components.MyLogin, HTMLStencilElement {
    }
    var HTMLMyLoginElement: {
        prototype: HTMLMyLoginElement;
        new (): HTMLMyLoginElement;
    };
    interface HTMLMyNavbarElement extends Components.MyNavbar, HTMLStencilElement {
    }
    var HTMLMyNavbarElement: {
        prototype: HTMLMyNavbarElement;
        new (): HTMLMyNavbarElement;
    };
    interface HTMLMyRegisterElement extends Components.MyRegister, HTMLStencilElement {
    }
    var HTMLMyRegisterElement: {
        prototype: HTMLMyRegisterElement;
        new (): HTMLMyRegisterElement;
    };
    interface HTMLMyUserElement extends Components.MyUser, HTMLStencilElement {
    }
    var HTMLMyUserElement: {
        prototype: HTMLMyUserElement;
        new (): HTMLMyUserElement;
    };
    interface HTMLOptionButtonsElement extends Components.OptionButtons, HTMLStencilElement {
    }
    var HTMLOptionButtonsElement: {
        prototype: HTMLOptionButtonsElement;
        new (): HTMLOptionButtonsElement;
    };
    interface HTMLShowDoctorElement extends Components.ShowDoctor, HTMLStencilElement {
    }
    var HTMLShowDoctorElement: {
        prototype: HTMLShowDoctorElement;
        new (): HTMLShowDoctorElement;
    };
    interface HTMLElementTagNameMap {
        "about-us": HTMLAboutUsElement;
        "app-about": HTMLAppAboutElement;
        "book-appointment": HTMLBookAppointmentElement;
        "circle-card": HTMLCircleCardElement;
        "doctor-list": HTMLDoctorListElement;
        "image-show": HTMLImageShowElement;
        "logo-login": HTMLLogoLoginElement;
        "my-adminnav": HTMLMyAdminnavElement;
        "my-appointment": HTMLMyAppointmentElement;
        "my-contactform": HTMLMyContactformElement;
        "my-error": HTMLMyErrorElement;
        "my-feedback": HTMLMyFeedbackElement;
        "my-footer": HTMLMyFooterElement;
        "my-heading": HTMLMyHeadingElement;
        "my-home": HTMLMyHomeElement;
        "my-image": HTMLMyImageElement;
        "my-login": HTMLMyLoginElement;
        "my-navbar": HTMLMyNavbarElement;
        "my-register": HTMLMyRegisterElement;
        "my-user": HTMLMyUserElement;
        "option-buttons": HTMLOptionButtonsElement;
        "show-doctor": HTMLShowDoctorElement;
    }
}
declare namespace LocalJSX {
    interface AboutUs {
    }
    interface AppAbout {
    }
    interface BookAppointment {
    }
    interface CircleCard {
    }
    interface DoctorList {
    }
    interface ImageShow {
    }
    interface LogoLogin {
    }
    interface MyAdminnav {
        "backColor"?: string;
        "fontFamily"?: string;
        "fontSize"?: string;
        "textColor"?: string;
    }
    interface MyAppointment {
    }
    interface MyContactform {
    }
    interface MyError {
        "message"?: string;
    }
    interface MyFeedback {
    }
    interface MyFooter {
        "Color"?: string;
    }
    interface MyHeading {
        "text"?: string;
    }
    interface MyHome {
    }
    interface MyImage {
    }
    interface MyLogin {
        "name"?: string;
    }
    interface MyNavbar {
        "backColor"?: string;
        "fontFamily"?: string;
        "fontSize"?: string;
        "textColor"?: string;
    }
    interface MyRegister {
    }
    interface MyUser {
    }
    interface OptionButtons {
    }
    interface ShowDoctor {
    }
    interface IntrinsicElements {
        "about-us": AboutUs;
        "app-about": AppAbout;
        "book-appointment": BookAppointment;
        "circle-card": CircleCard;
        "doctor-list": DoctorList;
        "image-show": ImageShow;
        "logo-login": LogoLogin;
        "my-adminnav": MyAdminnav;
        "my-appointment": MyAppointment;
        "my-contactform": MyContactform;
        "my-error": MyError;
        "my-feedback": MyFeedback;
        "my-footer": MyFooter;
        "my-heading": MyHeading;
        "my-home": MyHome;
        "my-image": MyImage;
        "my-login": MyLogin;
        "my-navbar": MyNavbar;
        "my-register": MyRegister;
        "my-user": MyUser;
        "option-buttons": OptionButtons;
        "show-doctor": ShowDoctor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-us": LocalJSX.AboutUs & JSXBase.HTMLAttributes<HTMLAboutUsElement>;
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "book-appointment": LocalJSX.BookAppointment & JSXBase.HTMLAttributes<HTMLBookAppointmentElement>;
            "circle-card": LocalJSX.CircleCard & JSXBase.HTMLAttributes<HTMLCircleCardElement>;
            "doctor-list": LocalJSX.DoctorList & JSXBase.HTMLAttributes<HTMLDoctorListElement>;
            "image-show": LocalJSX.ImageShow & JSXBase.HTMLAttributes<HTMLImageShowElement>;
            "logo-login": LocalJSX.LogoLogin & JSXBase.HTMLAttributes<HTMLLogoLoginElement>;
            "my-adminnav": LocalJSX.MyAdminnav & JSXBase.HTMLAttributes<HTMLMyAdminnavElement>;
            "my-appointment": LocalJSX.MyAppointment & JSXBase.HTMLAttributes<HTMLMyAppointmentElement>;
            "my-contactform": LocalJSX.MyContactform & JSXBase.HTMLAttributes<HTMLMyContactformElement>;
            "my-error": LocalJSX.MyError & JSXBase.HTMLAttributes<HTMLMyErrorElement>;
            "my-feedback": LocalJSX.MyFeedback & JSXBase.HTMLAttributes<HTMLMyFeedbackElement>;
            "my-footer": LocalJSX.MyFooter & JSXBase.HTMLAttributes<HTMLMyFooterElement>;
            "my-heading": LocalJSX.MyHeading & JSXBase.HTMLAttributes<HTMLMyHeadingElement>;
            "my-home": LocalJSX.MyHome & JSXBase.HTMLAttributes<HTMLMyHomeElement>;
            "my-image": LocalJSX.MyImage & JSXBase.HTMLAttributes<HTMLMyImageElement>;
            "my-login": LocalJSX.MyLogin & JSXBase.HTMLAttributes<HTMLMyLoginElement>;
            "my-navbar": LocalJSX.MyNavbar & JSXBase.HTMLAttributes<HTMLMyNavbarElement>;
            "my-register": LocalJSX.MyRegister & JSXBase.HTMLAttributes<HTMLMyRegisterElement>;
            "my-user": LocalJSX.MyUser & JSXBase.HTMLAttributes<HTMLMyUserElement>;
            "option-buttons": LocalJSX.OptionButtons & JSXBase.HTMLAttributes<HTMLOptionButtonsElement>;
            "show-doctor": LocalJSX.ShowDoctor & JSXBase.HTMLAttributes<HTMLShowDoctorElement>;
        }
    }
}
